import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  // Initialize with localStorage value or default to 'english'
  const getInitialLanguage = () => {
    const savedLanguage = localStorage.getItem('selectedLanguage');
    if (savedLanguage && ['english', 'hindi', 'tamil'].includes(savedLanguage)) {
      return savedLanguage;
    }
    return 'english';
  };

  const [language, setLanguage] = useState(getInitialLanguage);

  // Save language to localStorage when it changes
  useEffect(() => {
    if (language) {
      localStorage.setItem('selectedLanguage', language);
    }
  }, [language]);

  const translations = {
    english: {
      // Navigation
      home: 'Home',
      exercises: 'Exercises',
      journal: 'Journal',
      bookMentor: 'Book Mentor',
      growthReports: 'Growth Reports',
      settings: 'Settings',
      logout: 'Logout',

      // Greetings
      goodMorning: 'Good morning',
      goodAfternoon: 'Good afternoon',
      goodEvening: 'Good evening',

      // Sections
      todaysPractice: "Today's Practice",
      mindfulMoment: 'Mindful Moment',
      quickActions: 'Quick Actions',

      // Practices
      morningMeditation: 'Morning Meditation',
      breathingExercise: 'Breathing Exercise',
      eveningReflection: 'Evening Reflection',
      morningMeditationDesc: 'Start your day with clarity and focus',
      breathingExerciseDesc: 'Quick stress relief technique',
      eveningReflectionDesc: 'Wind down and reflect on your day',

      // Actions
      meditate: 'Meditate',
      reflect: 'Reflect',
      connect: 'Connect',
      progress: 'Progress',

      // Footer
      supportingWellness: 'Supporting Student Wellness at',
      buildingCommunities: 'Building healthier, more focused learning communities',

      // Language Selector
      selectLanguage: 'Select Language',
      english: 'English',
      hindi: 'हिंदी',
      tamil: 'தமிழ்',

      // Theme Toggle
      lightMode: 'Light',
      darkMode: 'Dark',

      // Welcome Page
      institutionalMindfulness: 'Institutional Mindfulness',
      bringingMeditation: 'Bringing meditation and mental wellness to schools and colleges',
      supportingStudentHealth: 'Supporting Student Mental Health',
      platformHelpsInstitutions: 'Our meditation platform helps educational institutions create calmer, more focused learning environments through daily mindfulness practice.',
      dailyMeditation: 'Daily Meditation',
      dailyMeditationDesc: 'Guided meditation sessions designed for academic stress relief',
      dailyMeditationBenefits: 'Reduces anxiety, improves concentration, builds resilience',
      mindfulReflection: 'Mindful Reflection',
      mindfulReflectionDesc: 'Structured journaling to process emotions and build awareness',
      mindfulReflectionBenefits: 'Enhances self-awareness, emotional regulation, academic performance',
      mentorSupport: 'Mentor Support',
      mentorSupportDesc: 'Connect with trained mindfulness mentors when you need guidance',
      mentorSupportBenefits: 'Personalized support, professional guidance, crisis intervention',
      simpleProgress: 'Simple Progress',
      simpleProgressDesc: 'Track your mindfulness journey with gentle encouragement',
      simpleProgressBenefits: 'Builds healthy habits, celebrates small wins, maintains motivation',
      meditationTools: 'Meditation & Mindfulness Tools',
      beginJourney: 'Begin Your Mindfulness Journey',
      getStartedStudent: 'Get Started as Student',
      joinAsMentor: 'Join as Mentor',
      adminAccess: 'Admin Access',
      supportingWellnessWorldwide: 'Supporting Student Wellness at Educational Institutions Worldwide',
      yourInstitution: 'Your Institution',

      // Institution Benefits
      reduceStress: 'Reduce student stress and anxiety levels by up to 40%',
      improveFocus: 'Improve academic focus and concentration',
      supportWellness: 'Support mental health and emotional well-being',
      buildResilience: 'Build resilience against academic pressure',
      fosterEnvironments: 'Foster positive learning environments',
      hipaaCompliant: 'HIPAA-compliant with institutional data security',

      // Login Page
      welcomeBack: 'Welcome Back',
      signInAccount: 'Sign in to your account',
      email: 'Email',
      password: 'Password',
      signIn: 'Sign In',
      forgotPassword: 'Forgot Password?',
      noAccount: "Don't have an account?",
      signUp: 'Sign Up',
      invalidCredentials: 'Invalid email or password',
      loginSuccess: 'Login successful!',
      alreadyHaveAccount: 'Already have an account?',

      // Profile Setup
      completeProfile: 'Complete Your Profile',
      personalInfo: 'Personal Information',
      fullName: 'Full Name',
      institution: 'Institution',
      role: 'Role',
      student: 'Student',
      mentor: 'Mentor',
      admin: 'Administrator',
      continue: 'Continue',
      profileSetupSuccess: 'Profile setup completed successfully!',

      // Mindfulness Exercises
      meditationSessions: 'Meditation Sessions',
      guidedMeditations: 'Guided Meditations',
      breathingTechniques: 'Breathing Techniques',
      bodyScan: 'Body Scan Meditation',
      lovingKindness: 'Loving-Kindness Meditation',
      startSession: 'Start Session',
      sessionComplete: 'Session Complete!',
      minutesRemaining: 'minutes remaining',
      pause: 'Pause',
      resume: 'Resume',
      complete: 'Complete',
      guidedStories: 'Guided Stories',
      guidedStoriesDesc: 'Immersive audio stories designed to promote relaxation and mindfulness.',
      breathingExercises: 'Breathing Exercises',
      breathingExercisesDesc: 'Simple breathing techniques to reduce stress and improve focus.',
      reflectionPrompts: 'Reflection Prompts',
      reflectionPromptsDesc: 'Thought-provoking questions to encourage self-reflection.',
      psychometricTests: 'Psychometric Tests',
      psychometricTestsDesc: 'Assess your mental health and track your progress over time.',
      startStory: 'Start Story',
      beginExercise: 'Begin Exercise',
      reflectNow: 'Reflect Now',
      takeTest: 'Take Test',
      recentActivity: 'Recent Activity',
      lastCompleted: 'Last completed',
      timeSpentWeek: 'Time spent this week',

      // Journal
      dailyJournal: 'Daily Journal',
      newEntry: 'New Entry',
      todaysThoughts: "Today's Thoughts",
      howFeeling: 'How are you feeling today?',
      gratefulFor: 'What are you grateful for?',
      challenges: 'What challenges did you face?',
      tomorrowGoals: 'What are your goals for tomorrow?',
      saveEntry: 'Save Entry',
      journalSaved: 'Journal entry saved successfully!',
      journalDesc: 'Reflect on your thoughts, experiences, and growth journey',
      reflectionPromptsTitle: 'Reflection Prompts',
      journalHistory: 'Journal History',
      entriesThisWeek: 'Entries this week',
      longestStreak: 'Longest streak',
      totalEntries: 'Total entries',

      // Book Mentor
      bookMentorTitle: 'Book a Mentor Session',
      sessionManagementDesc: 'Oversee all mentoring sessions and manage scheduling',
      sessionOverview: 'Session Overview',
      totalSessions: 'Total Sessions',
      completed: 'Completed',
      scheduled: 'Scheduled',
      quickActions: 'Quick Actions',
      scheduleSession: 'Schedule Session',
      manageMentors: 'Manage Mentors',
      viewReports: 'View Reports',
      allSessions: 'All Sessions',
      student: 'Student',
      mentor: 'Mentor',
      dateTime: 'Date & Time',
      topic: 'Topic',
      status: 'Status',
      actions: 'Actions',

      // Growth Reports
      growthReportsTitle: 'Growth Reports',
      trackProgress: 'Track your progress and celebrate your achievements',
      backToDashboard: 'Back to Dashboard',
      weeklyProgress: 'Weekly Progress',
      meditationStreak: 'Meditation Streak',
      journalEntries: 'Journal Entries',
      moodTrends: 'Mood Trends',
      achievements: 'Achievements',
      days: 'days',
      entries: 'entries',
      viewDetails: 'View Details',

      // Settings
      settingsTitle: 'Settings',
      accountSettings: 'Account Settings',
      notificationSettings: 'Notification Settings',
      privacySettings: 'Privacy Settings',
      languageSettings: 'Language Settings',
      changePassword: 'Change Password',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmPassword: 'Confirm Password',
      updatePassword: 'Update Password',
      enableNotifications: 'Enable Notifications',
      emailNotifications: 'Email Notifications',
      pushNotifications: 'Push Notifications',
      saveSettings: 'Save Settings',
      settingsSaved: 'Settings saved successfully!',
      sessionReminders: 'Session reminders',
      dailyWellnessCheckins: 'Daily wellness check-ins',
      exerciseSuggestions: 'Exercise suggestions',
      weeklyProgressReports: 'Weekly progress reports',
      dataSharing: 'Data sharing',
      private: 'Private',
      shareWithInstitution: 'Share with institution',
      public: 'Public',
      twoFactorAuth: 'Two-factor authentication',
      enable: 'Enable',
      helpSupport: 'Help & Support',
      userGuide: 'User Guide',
      contactSupport: 'Contact Support',
      faq: 'FAQ',

      // Notifications
      notificationsTitle: 'Notifications',
      stayUpdated: 'Stay updated with your mindfulness journey',
      recentNotifications: 'Recent Notifications',
      markAsRead: 'Mark as Read',
      delete: 'Delete',
      all: 'All',
      unread: 'Unread',
      sessionReminder: 'Session Reminder',
      sessionReminderMessage: 'Your mentor session with Dr. Smith is in 30 minutes',
      exerciseSuggestion: 'Exercise Suggestion',
      exerciseSuggestionMessage: 'Try the "Breathing Space" exercise - perfect for stressful moments',
      streakMilestone: 'Streak Milestone!',
      streakMilestoneMessage: 'Congratulations! You\'ve completed 7 days in a row',
      dailyCheckin: 'Daily Check-in',
      dailyCheckinMessage: 'How are you feeling today? Don\'t forget to log your mood',
      sessionFollowup: 'Session Follow-up',
      sessionFollowupMessage: 'How did your last session go? Share your reflections in your journal',
      achievementNotifications: 'Achievement Notifications',

      // Analytics
      analyticsTitle: 'Analytics',
      comprehensiveInsights: 'Comprehensive insights for',
      yourInstitution: 'your institution',
      userEngagement: 'User Engagement',
      programPerformance: 'Program Performance',
      mostPopularExercises: 'Most Popular Exercises',
      totalUsers: 'Total Users',
      activeUsers: 'Active Users',
      sessionsCompleted: 'Sessions Completed',
      averageMoodScore: 'Average Mood Score',
      exercisesCompleted: 'Exercises Completed',
      participationRate: 'Participation Rate',
      averageSessionTime: 'Average Session Time',
      meditationStats: 'Meditation Statistics',
      journalStats: 'Journal Statistics',
      mentorSessions: 'Mentor Sessions',
      topExercises: 'Top Exercises',
      moodTrends: 'Mood Trends',
      institutionOverview: 'Institution Overview',
      totalInstitutions: 'Total Institutions',
      activePrograms: 'Active Programs',
      topPerformer: 'Top Performer',
      thisWeek: 'This Week',
      thisMonth: 'This Month',
      thisQuarter: 'This Quarter',
      refresh: 'Refresh',
      exportData: 'Export Data',
      exportingData: 'Exporting data...',
      refreshingData: 'Refreshing data...',
      breathingExercises: 'Breathing Exercises',
      bodyScan: 'Body Scan',
      mindfulWalking: 'Mindful Walking',
      lovingKindness: 'Loving Kindness',
      week1: 'Week 1',
      week2: 'Week 2',
      week3: 'Week 3',
      week4: 'Week 4',

      // Common
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      cancel: 'Cancel',
      save: 'Save',
      edit: 'Edit',
      delete: 'Delete',
      back: 'Back',
      next: 'Next',
      previous: 'Previous',
      search: 'Search',
      filter: 'Filter',
      sort: 'Sort',
      date: 'Date',
      time: 'Time',
      duration: 'Duration',
      status: 'Status',
      actions: 'Actions'
    },
    hindi: {
      // Navigation
      home: 'होम',
      exercises: 'अभ्यास',
      journal: 'दैनिकी',
      bookMentor: 'मेंटर बुक करें',
      growthReports: 'विकास रिपोर्ट',
      settings: 'सेटिंग्स',
      logout: 'लॉगआउट',

      // Greetings
      goodMorning: 'सुप्रभात',
      goodAfternoon: 'नमस्ते',
      goodEvening: 'शुभ संध्या',

      // Sections
      todaysPractice: 'आज का अभ्यास',
      mindfulMoment: 'सजग पल',
      quickActions: 'तेज़ कार्य',

      // Practices
      morningMeditation: 'सुबह का ध्यान',
      breathingExercise: 'श्वास अभ्यास',
      eveningReflection: 'शाम की प्रतिबिंब',
      morningMeditationDesc: 'स्पष्टता और फोकस के साथ अपना दिन शुरू करें',
      breathingExerciseDesc: 'तत्काल तनाव राहत तकनीक',
      eveningReflectionDesc: 'अपने दिन पर विचार करें',

      // Actions
      meditate: 'ध्यान करें',
      reflect: 'विचार करें',
      connect: 'जुड़ें',
      progress: 'प्रगति',

      // Footer
      supportingWellness: 'छात्र कल्याण का समर्थन',
      buildingCommunities: 'स्वस्थ और अधिक केंद्रित सीखने समुदायों का निर्माण',

      // Language Selector
      selectLanguage: 'भाषा चुनें',
      english: 'English',
      hindi: 'हिंदी',
      tamil: 'தமிழ்',

      // Theme Toggle
      lightMode: 'लाइट',
      darkMode: 'डार्क',

      // Welcome Page
      institutionalMindfulness: 'संस्थागत ध्यान',
      bringingMeditation: 'स्कूलों और कॉलेजों में ध्यान और मानसिक कल्याण लाना',
      supportingStudentHealth: 'छात्र मानसिक स्वास्थ्य का समर्थन',
      platformHelpsInstitutions: 'हमारा ध्यान प्लेटफॉर्म दैनिक ध्यान अभ्यास के माध्यम से शैक्षणिक संस्थानों को अधिक शांत और केंद्रित सीखने के वातावरण बनाने में मदद करता है।',
      dailyMeditation: 'दैनिक ध्यान',
      dailyMeditationDesc: 'शैक्षणिक तनाव राहत के लिए डिज़ाइन किए गए निर्देशित ध्यान सत्र',
      dailyMeditationBenefits: 'चिंता कम करता है, एकाग्रता में सुधार करता है, लचीलापन बनाता है',
      mindfulReflection: 'सजग प्रतिबिंब',
      mindfulReflectionDesc: 'भावनाओं को संसाधित करने और जागरूकता बनाने के लिए संरचित journaling',
      mindfulReflectionBenefits: 'आत्म-जागरूकता बढ़ाता है, भावनात्मक नियमन, शैक्षणिक प्रदर्शन',
      mentorSupport: 'मेंटर समर्थन',
      mentorSupportDesc: 'जब आपको मार्गदर्शन की आवश्यकता हो तो प्रशिक्षित ध्यान मेंटर से जुड़ें',
      mentorSupportBenefits: 'व्यक्तिगत समर्थन, पेशेवर मार्गदर्शन, संकट हस्तक्षेप',
      simpleProgress: 'सरल प्रगति',
      simpleProgressDesc: 'सौम्य प्रोत्साहन के साथ अपने ध्यान यात्रा को ट्रैक करें',
      simpleProgressBenefits: 'स्वस्थ आदतें बनाता है, छोटी जीतों का जश्न मनाता है, प्रेरणा बनाए रखता है',
      meditationTools: 'ध्यान और सजगता उपकरण',
      beginJourney: 'अपनी सजगता यात्रा शुरू करें',
      getStartedStudent: 'छात्र के रूप में शुरू करें',
      joinAsMentor: 'मेंटर के रूप में शामिल हों',
      adminAccess: 'व्यवस्थापक पहुंच',
      supportingWellnessWorldwide: 'पूरे विश्व में शैक्षणिक संस्थानों में छात्र कल्याण का समर्थन',
      yourInstitution: 'आपकी संस्था',

      // Institution Benefits
      reduceStress: 'छात्रों के तनाव और चिंता के स्तर को 40% तक कम करें',
      improveFocus: 'शैक्षणिक फोकस और एकाग्रता में सुधार करें',
      supportWellness: 'मानसिक स्वास्थ्य और भावनात्मक भलाई का समर्थन करें',
      buildResilience: 'शैक्षणिक दबाव के खिलाफ लचीलापन बनाएं',
      fosterEnvironments: 'सकारात्मक सीखने के वातावरण को बढ़ावा दें',
      hipaaCompliant: 'संस्थागत डेटा सुरक्षा के साथ HIPAA-अनुपालित',

      // Login Page
      welcomeBack: 'वापसी पर स्वागत',
      signInAccount: 'अपने खाते में साइन इन करें',
      email: 'ईमेल',
      password: 'पासवर्ड',
      signIn: 'साइन इन',
      forgotPassword: 'पासवर्ड भूल गए?',
      noAccount: 'खाता नहीं है?',
      signUp: 'साइन अप',
      invalidCredentials: 'अमान्य ईमेल या पासवर्ड',
      loginSuccess: 'लॉगिन सफल!',
      alreadyHaveAccount: 'पहले से खाता है?',

      // Profile Setup
      completeProfile: 'अपनी प्रोफ़ाइल पूरा करें',
      personalInfo: 'व्यक्तिगत जानकारी',
      fullName: 'पूरा नाम',
      institution: 'संस्था',
      role: 'भूमिका',
      student: 'छात्र',
      mentor: 'मेंटर',
      admin: 'व्यवस्थापक',
      continue: 'जारी रखें',
      profileSetupSuccess: 'प्रोफ़ाइल सेटअप सफलतापूर्वक पूरा हुआ!',

      // Mindfulness Exercises
      meditationSessions: 'ध्यान सत्र',
      guidedMeditations: 'निर्देशित ध्यान',
      breathingTechniques: 'श्वास तकनीकें',
      bodyScan: 'शरीर स्कैन ध्यान',
      lovingKindness: 'प्रेम-करुणा ध्यान',
      startSession: 'सत्र शुरू करें',
      sessionComplete: 'सत्र पूरा!',
      minutesRemaining: 'मिनट शेष',
      pause: 'रोकें',
      resume: 'पुनः शुरू करें',
      complete: 'पूरा करें',
      guidedStories: 'निर्देशित कहानियाँ',
      guidedStoriesDesc: 'आराम और सजगता को बढ़ावा देने के लिए डिज़ाइन किए गए immersive ऑडियो कहानियाँ।',
      breathingExercises: 'श्वास अभ्यास',
      breathingExercisesDesc: 'तनाव कम करने और फोकस में सुधार करने के लिए सरल श्वास तकनीकें।',
      reflectionPrompts: 'प्रतिबिंब संकेत',
      reflectionPromptsDesc: 'आत्म-प्रतिबिंब को प्रोत्साहित करने के लिए विचारोत्तेजक प्रश्न।',
      psychometricTests: 'मनोवैज्ञानिक परीक्षण',
      psychometricTestsDesc: 'अपने मानसिक स्वास्थ्य का आकलन करें और समय के साथ अपनी प्रगति को ट्रैक करें।',
      startStory: 'कहानी शुरू करें',
      beginExercise: 'अभ्यास शुरू करें',
      reflectNow: 'अभी प्रतिबिंब करें',
      takeTest: 'परीक्षण लें',
      recentActivity: 'हाल की गतिविधि',
      lastCompleted: 'अंतिम पूरा किया गया',
      timeSpentWeek: 'इस सप्ताह बिताया गया समय',

      // Journal
      dailyJournal: 'दैनिक दैनिकी',
      newEntry: 'नई प्रविष्टि',
      todaysThoughts: 'आज के विचार',
      howFeeling: 'आज आप कैसा महसूस कर रहे हैं?',
      gratefulFor: 'आप किसके लिए आभारी हैं?',
      challenges: 'आपको कौन सी चुनौतियां सामने आईं?',
      tomorrowGoals: 'कल के आपके लक्ष्य क्या हैं?',
      saveEntry: 'प्रविष्टि सहेजें',
      journalSaved: 'दैनिकी प्रविष्टि सफलतापूर्वक सहेजी गई!',
      journalDesc: 'अपने विचारों, अनुभवों और विकास यात्रा पर विचार करें',
      reflectionPromptsTitle: 'प्रतिबिंब संकेत',
      journalHistory: 'दैनिकी इतिहास',
      entriesThisWeek: 'इस सप्ताह प्रविष्टियां',
      longestStreak: 'लंबी श्रृंखला',
      totalEntries: 'कुल प्रविष्टियां',

      // Book Mentor
      bookMentorTitle: 'मेंटर सत्र बुक करें',
      sessionManagementDesc: 'सभी मेंटरिंग सत्रों की देखरेख करें और शेड्यूलिंग प्रबंधित करें',
      sessionOverview: 'सत्र अवलोकन',
      totalSessions: 'कुल सत्र',
      completed: 'पूर्ण',
      scheduled: 'निर्धारित',
      quickActions: 'तेज़ कार्य',
      scheduleSession: 'सत्र निर्धारित करें',
      manageMentors: 'मेंटर प्रबंधित करें',
      viewReports: 'रिपोर्ट देखें',
      allSessions: 'सभी सत्र',
      student: 'छात्र',
      mentor: 'मेंटर',
      dateTime: 'दिनांक और समय',
      topic: 'विषय',
      status: 'स्थिति',
      actions: 'कार्रवाई',

      // Growth Reports
      growthReportsTitle: 'विकास रिपोर्ट',
      trackProgress: 'अपनी प्रगति को ट्रैक करें और अपनी उपलब्धियों का जश्न मनाएं',
      backToDashboard: 'डैशबोर्ड पर वापस',
      weeklyProgress: 'साप्ताहिक प्रगति',
      meditationStreak: 'ध्यान श्रृंखला',
      journalEntries: 'दैनिकी प्रविष्टियां',
      moodTrends: 'मूड प्रवृत्तियां',
      achievements: 'उपलब्धियां',
      days: 'दिन',
      entries: 'प्रविष्टियां',
      viewDetails: 'विवरण देखें',

      // Settings
      settingsTitle: 'सेटिंग्स',
      accountSettings: 'खाता सेटिंग्स',
      notificationSettings: 'सूचना सेटिंग्स',
      privacySettings: 'गोपनीयता सेटिंग्स',
      languageSettings: 'भाषा सेटिंग्स',
      changePassword: 'पासवर्ड बदलें',
      currentPassword: 'वर्तमान पासवर्ड',
      newPassword: 'नया पासवर्ड',
      confirmPassword: 'पासवर्ड की पुष्टि करें',
      updatePassword: 'पासवर्ड अपडेट करें',
      enableNotifications: 'सूचनाएं सक्षम करें',
      emailNotifications: 'ईमेल सूचनाएं',
      pushNotifications: 'पुश सूचनाएं',
      saveSettings: 'सेटिंग्स सहेजें',
      settingsSaved: 'सेटिंग्स सफलतापूर्वक सहेजी गईं!',
      sessionReminders: 'सत्र अनुस्मारक',
      dailyWellnessCheckins: 'दैनिक कल्याण जांच',
      exerciseSuggestions: 'अभ्यास सुझाव',
      weeklyProgressReports: 'साप्ताहिक प्रगति रिपोर्ट',
      dataSharing: 'डेटा साझा करना',
      private: 'निजी',
      shareWithInstitution: 'संस्था के साथ साझा करें',
      public: 'सार्वजनिक',
      twoFactorAuth: 'दो-कारक प्रमाणीकरण',
      enable: 'सक्षम करें',
      helpSupport: 'सहायता और समर्थन',
      userGuide: 'उपयोगकर्ता गाइड',
      contactSupport: 'संपर्क सहायता',
      faq: 'सामान्य प्रश्न',

      // Notifications
      notificationsTitle: 'सूचनाएं',
      stayUpdated: 'अपनी सजगता यात्रा के साथ अपडेट रहें',
      recentNotifications: 'हाल की सूचनाएं',
      markAsRead: 'पढ़ा हुआ चिह्नित करें',
      delete: 'मिटाएं',
      all: 'सभी',
      unread: 'अपठित',
      sessionReminder: 'सत्र अनुस्मारक',
      sessionReminderMessage: 'डॉ. स्मिथ के साथ आपका मेंटर सत्र 30 मिनट में है',
      exerciseSuggestion: 'अभ्यास सुझाव',
      exerciseSuggestionMessage: '"श्वास स्थान" अभ्यास आज़माएं - तनावपूर्ण क्षणों के लिए परफेक्ट',
      streakMilestone: 'श्रृंखला मील का पत्थर!',
      streakMilestoneMessage: 'बधाई हो! आपने लगातार 7 दिन पूरे किए हैं',
      dailyCheckin: 'दैनिक जांच',
      dailyCheckinMessage: 'आज आप कैसा महसूस कर रहे हैं? अपना मूड लॉग करना न भूलें',
      sessionFollowup: 'सत्र अनुवर्ती कार्रवाई',
      sessionFollowupMessage: 'आपका पिछला सत्र कैसा गया? अपने दैनिकी में अपनी प्रतिबिंब साझा करें',
      achievementNotifications: 'उपलब्धि सूचनाएं',

      // Analytics
      analyticsTitle: 'विश्लेषण',
      comprehensiveInsights: 'के लिए व्यापक अंतर्दृष्टि',
      yourInstitution: 'आपकी संस्था',
      userEngagement: 'उपयोगकर्ता सहभागिता',
      programPerformance: 'कार्यक्रम प्रदर्शन',
      mostPopularExercises: 'सर्वाधिक लोकप्रिय अभ्यास',
      totalUsers: 'कुल उपयोगकर्ता',
      activeUsers: 'सक्रिय उपयोगकर्ता',
      sessionsCompleted: 'पूर्ण सत्र',
      averageMoodScore: 'औसत मूड स्कोर',
      exercisesCompleted: 'पूर्ण अभ्यास',
      participationRate: 'सहभागिता दर',
      averageSessionTime: 'औसत सत्र समय',
      meditationStats: 'ध्यान आंकड़े',
      journalStats: 'दैनिकी आंकड़े',
      mentorSessions: 'मेंटर सत्र',
      topExercises: 'शीर्ष अभ्यास',
      moodTrends: 'मूड प्रवृत्तियां',
      institutionOverview: 'संस्था अवलोकन',
      totalInstitutions: 'कुल संस्थाएं',
      activePrograms: 'सक्रिय कार्यक्रम',
      topPerformer: 'शीर्ष प्रदर्शक',
      thisWeek: 'इस सप्ताह',
      thisMonth: 'इस महीने',
      thisQuarter: 'इस तिमाही',
      refresh: 'रीफ्रेश',
      exportData: 'डेटा निर्यात करें',
      exportingData: 'डेटा निर्यात हो रहा है...',
      refreshingData: 'डेटा रिफ्रेश हो रहा है...',
      breathingExercises: 'श्वास अभ्यास',
      bodyScan: 'शरीर स्कैन',
      mindfulWalking: 'सजग पैदल चलना',
      lovingKindness: 'प्रेम-करुणा',
      week1: 'सप्ताह 1',
      week2: 'सप्ताह 2',
      week3: 'सप्ताह 3',
      week4: 'सप्ताह 4',

      // Common
      loading: 'लोड हो रहा है...',
      error: 'त्रुटि',
      success: 'सफलता',
      cancel: 'रद्द करें',
      save: 'सहेजें',
      edit: 'संपादित करें',
      delete: 'मिटाएं',
      back: 'वापस',
      next: 'अगला',
      previous: 'पिछला',
      search: 'खोजें',
      filter: 'फिल्टर',
      sort: 'क्रमबद्ध करें',
      date: 'दिनांक',
      time: 'समय',
      duration: 'अवधि',
      status: 'स्थिति',
      actions: 'कार्रवाई'
    },
    tamil: {
      // Navigation
      home: 'முகப்பு',
      exercises: 'பயிற்சிகள்',
      journal: 'நாட்குறிப்பு',
      bookMentor: 'மென்டரை முன்பதிவு செய்ய',
      growthReports: 'வளர்ச்சி அறிக்கைகள்',
      settings: 'அமைப்புகள்',
      logout: 'வெளியேறு',

      // Greetings
      goodMorning: 'காலை வணக்கம்',
      goodAfternoon: 'மதிய வணக்கம்',
      goodEvening: 'மாலை வணக்கம்',

      // Sections
      todaysPractice: 'இன்றைய பயிற்சி',
      mindfulMoment: 'உணர்வு நொடி',
      quickActions: 'விரைவு செயல்கள்',

      // Practices
      morningMeditation: 'காலை தியானம்',
      breathingExercise: 'மூச்சு பயிற்சி',
      eveningReflection: 'மாலை சிந்தனை',
      morningMeditationDesc: 'தெளிவு மற்றும் கவனத்துடன் உங்கள் நாளைத் தொடங்குங்கள்',
      breathingExerciseDesc: 'விரைவான மன அழுத்த நிவாரண நுட்பம்',
      eveningReflectionDesc: 'உங்கள் நாளைப் பற்றி சிந்திக்கவும்',

      // Actions
      meditate: 'தியானம் செய்ய',
      reflect: 'பிரதிபலிக்க',
      connect: 'இணைக்க',
      progress: 'முன்னேற்றம்',

      // Footer
      supportingWellness: 'மாணவர் நலனை ஆதரித்தல்',
      buildingCommunities: 'ஆரோக்கியமான மற்றும் அதிக கவனம் செலுத்தும் கற்றல் சமூகங்களை உருவாக்குதல்',

      // Language Selector
      selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
      english: 'English',
      hindi: 'हिंदी',
      tamil: 'தமிழ்',

      // Theme Toggle
      lightMode: 'ஒளி',
      darkMode: 'இருள்',

      // Welcome Page
      institutionalMindfulness: 'நிறுவன உணர்வு',
      bringingMeditation: 'பள்ளிகள் மற்றும் கல்லூரிகளுக்கு தியானம் மற்றும் மனநலத்தை கொண்டு வருதல்',
      supportingStudentHealth: 'மாணவர் மனநலத்தை ஆதரித்தல்',
      platformHelpsInstitutions: 'எங்கள் தியான தளம் தினசரி தியான பயிற்சி மூலம் கல்வி நிறுவனங்களுக்கு அமைதியான மற்றும் அதிக கவனம் செலுத்தும் கற்றல் சூழலை உருவாக்க உதவுகிறது.',
      dailyMeditation: 'தினசரி தியானம்',
      dailyMeditationDesc: 'கல்வி மன அழுத்த நிவாரணத்திற்காக வடிவமைக்கப்பட்ட வழிகாட்டப்பட்ட தியான அமர்வுகள்',
      dailyMeditationBenefits: 'பதற்றத்தை குறைக்கிறது, கவனத்தை மேம்படுத்துகிறது, வலிமையை உருவாக்குகிறது',
      mindfulReflection: 'உணர்வு பிரதிபலிப்பு',
      mindfulReflectionDesc: 'உணர்வுகளை செயலாக்க மற்றும் விழிப்புணர்வை உருவாக்குவதற்கான கட்டமைக்கப்பட்ட நாட்குறிப்பு',
      mindfulReflectionBenefits: 'சுய விழிப்புணர்வை மேம்படுத்துகிறது, உணர்வு ஒழுங்குமுறை, கல்வி செயல்பாடு',
      mentorSupport: 'மென்டர் ஆதரவு',
      mentorSupportDesc: 'உங்களுக்கு வழிகாட்டல் தேவைப்படும்போது பயிற்சி பெற்ற தியான மென்டர்களுடன் இணைக்கவும்',
      mentorSupportBenefits: 'தனிப்பட்ட ஆதரவு, தொழில்முறை வழிகாட்டல், நெருக்கடி தலையீடு',
      simpleProgress: 'எளிய முன்னேற்றம்',
      simpleProgressDesc: 'மென்மையான ஊக்கத்துடன் உங்கள் தியான பயணத்தை கண்காணிக்கவும்',
      simpleProgressBenefits: 'ஆரோக்கியமான பழக்கங்களை உருவாக்குகிறது, சிறிய வெற்றிகளை கொண்டாடுகிறது, உந்துதலை பராமரிக்கிறது',
      meditationTools: 'தியானம் மற்றும் உணர்வு கருவிகள்',
      beginJourney: 'உங்கள் உணர்வு பயணத்தைத் தொடங்குங்கள்',
      getStartedStudent: 'மாணவராகத் தொடங்குங்கள்',
      joinAsMentor: 'மென்டராக இணைக்கவும்',
      adminAccess: 'நிர்வாகி அணுகல்',
      supportingWellnessWorldwide: 'உலகெங்கிலும் கல்வி நிறுவனங்களில் மாணவர் நலனை ஆதரித்தல்',
      yourInstitution: 'உங்கள் நிறுவனம்',

      // Institution Benefits
      reduceStress: 'மாணவர் மன அழுத்தம் மற்றும் பதற்ற நிலைகளை 40% வரை குறைக்கவும்',
      improveFocus: 'கல்வி கவனம் மற்றும் ஒருமைப்பாட்டை மேம்படுத்தவும்',
      supportWellness: 'மனநலம் மற்றும் உணர்வு நலனை ஆதரிக்கவும்',
      buildResilience: 'கல்வி அழுத்தத்திற்கு எதிராக வலிமையை உருவாக்கவும்',
      fosterEnvironments: 'நேர்மறையான கற்றல் சூழலை ஊக்குவிக்கவும்',
      hipaaCompliant: 'நிறுவன தரவு பாதுகாப்புடன் HIPAA இணங்கியது',

      // Login Page
      welcomeBack: 'மீண்டும் வருக',
      signInAccount: 'உங்கள் கணக்கில் உள்நுழையவும்',
      email: 'மின்னஞ்சல்',
      password: 'கடவுச்சொல்',
      signIn: 'உள்நுழைய',
      forgotPassword: 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
      noAccount: 'கணக்கு இல்லையா?',
      signUp: 'பதிவு செய்ய',
      invalidCredentials: 'தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்',
      loginSuccess: 'உள்நுழைவு வெற்றிகரமாக!',
      alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',

      // Profile Setup
      completeProfile: 'உங்கள் சுயவிவரத்தை முழுமையாக்குங்கள்',
      personalInfo: 'தனிப்பட்ட தகவல்',
      fullName: 'முழு பெயர்',
      institution: 'நிறுவனம்',
      role: 'பங்கு',
      student: 'மாணவர்',
      mentor: 'மென்டர்',
      admin: 'நிர்வாகி',
      continue: 'தொடரவும்',
      profileSetupSuccess: 'சுயவிவர அமைப்பு வெற்றிகரமாக முடிந்தது!',

      // Mindfulness Exercises
      meditationSessions: 'தியான அமர்வுகள்',
      guidedMeditations: 'வழிகாட்டப்பட்ட தியானங்கள்',
      breathingTechniques: 'மூச்சு நுட்பங்கள்',
      bodyScan: 'உடல் ஸ்கேன் தியானம்',
      lovingKindness: 'அன்பு-நன்மை தியானம்',
      startSession: 'அமர்வைத் தொடங்கு',
      sessionComplete: 'அமர்வு முழுமையடைந்தது!',
      minutesRemaining: 'நிமிடங்கள் மீதமுள்ளன',
      pause: 'இடைநிறுத்து',
      resume: 'தொடரவும்',
      complete: 'முழுமையாக்கு',
      guidedStories: 'வழிகாட்டப்பட்ட கதைகள்',
      guidedStoriesDesc: 'ஆரோக்கியம் மற்றும் உணர்வை ஊக்குவிக்க வடிவமைக்கப்பட்ட மூழ்கும் ஆடியோ கதைகள்.',
      breathingExercises: 'மூச்சு பயிற்சிகள்',
      breathingExercisesDesc: 'மன அழுத்தத்தை குறைக்க மற்றும் கவனத்தை மேம்படுத்த எளிய மூச்சு நுட்பங்கள்.',
      reflectionPrompts: 'பிரதிபலிப்பு கேள்விகள்',
      reflectionPromptsDesc: 'சுய பிரதிபலிப்பை ஊக்குவிக்கும் எண்ணங்களைத் தூண்டும் கேள்விகள்.',
      psychometricTests: 'மனநல சோதனைகள்',
      psychometricTestsDesc: 'உங்கள் மனநலத்தை மதிப்பிடுங்கள் மற்றும் காலப்போக்கில் உங்கள் முன்னேற்றத்தை கண்காணிக்கவும்.',
      startStory: 'கதையைத் தொடங்கு',
      beginExercise: 'பயிற்சியைத் தொடங்கு',
      reflectNow: 'இப்போது பிரதிபலிக்கவும்',
      takeTest: 'சோதனையை எடுக்கவும்',
      recentActivity: 'சமீபத்திய செயல்பாடு',
      lastCompleted: 'கடைசியாக முழுமையடைந்தது',
      timeSpentWeek: 'இந்த வாரம் செலவழித்த நேரம்',

      // Journal
      dailyJournal: 'தினசரி நாட்குறிப்பு',
      newEntry: 'புதிய உள்ளீடு',
      todaysThoughts: 'இன்றைய எண்ணங்கள்',
      howFeeling: 'இன்று நீங்கள் எவ்வாறு உணர்கிறீர்கள்?',
      gratefulFor: 'நீங்கள் எதற்கு நன்றியுள்ளீர்கள்?',
      challenges: 'நீங்கள் எந்த சவால்களை எதிர்கொண்டீர்கள்?',
      tomorrowGoals: 'நாளைய உங்கள் இலக்குகள் என்ன?',
      saveEntry: 'உள்ளீட்டைச் சேமிக்கவும்',
      journalSaved: 'நாட்குறிப்பு உள்ளீடு வெற்றிகரமாக சேமிக்கப்பட்டது!',
      journalDesc: 'உங்கள் எண்ணங்கள், அனுபவங்கள் மற்றும் வளர்ச்சி பயணத்தில் பிரதிபலிக்கவும்',
      reflectionPromptsTitle: 'பிரதிபலிப்பு கேள்விகள்',
      journalHistory: 'நாட்குறிப்பு வரலாறு',
      entriesThisWeek: 'இந்த வாரம் உள்ளீடுகள்',
      longestStreak: 'நீண்ட தொடர்',
      totalEntries: 'மொத்த உள்ளீடுகள்',

      // Book Mentor
      bookMentorTitle: 'மென்டர் அமர்வை முன்பதிவு செய்யவும்',
      sessionManagementDesc: 'அனைத்து மென்டரிங் அமர்வுகளையும் மேற்பார்வையிடவும் மற்றும் திட்டமிடலை நிர்வகிக்கவும்',
      sessionOverview: 'அமர்வு கண்ணோட்டம்',
      totalSessions: 'மொத்த அமர்வுகள்',
      completed: 'முழுமையடைந்தது',
      scheduled: 'திட்டமிடப்பட்டது',
      quickActions: 'விரைவு செயல்கள்',
      scheduleSession: 'அமர்வைத் திட்டமிடுங்கள்',
      manageMentors: 'மென்டர்களை நிர்வகிக்கவும்',
      viewReports: 'அறிக்கைகளைக் காண்க',
      allSessions: 'அனைத்து அமர்வுகளும்',
      student: 'மாணவர்',
      mentor: 'மென்டர்',
      dateTime: 'தேதி மற்றும் நேரம்',
      topic: 'தலைப்பு',
      status: 'நிலை',
      actions: 'செயல்கள்',

      // Growth Reports
      growthReportsTitle: 'வளர்ச்சி அறிக்கைகள்',
      trackProgress: 'உங்கள் முன்னேற்றத்தை கண்காணித்து உங்கள் சாதனைகளை கொண்டாடுங்கள்',
      backToDashboard: 'டாஷ்போர்டுக்கு திரும்பு',
      weeklyProgress: 'வாராந்திர முன்னேற்றம்',
      meditationStreak: 'தியான தொடர்',
      journalStreak: 'நாட்குறிப்பு தொடர்',
      journalEntries: 'நாட்குறிப்பு உள்ளீடுகள்',
      moodTrends: 'மனநிலை போக்குகள்',
      achievements: 'சாதனைகள்',
      days: 'நாட்கள்',
      entries: 'உள்ளீடுகள்',
      viewDetails: 'விவரங்களைக் காண்க',

      // Settings
      settingsTitle: 'அமைப்புகள்',
      accountSettings: 'கணக்கு அமைப்புகள்',
      notificationSettings: 'அறிவிப்பு அமைப்புகள்',
      privacySettings: 'தனியுரிமை அமைப்புகள்',
      languageSettings: 'மொழி அமைப்புகள்',
      changePassword: 'கடவுச்சொல்லை மாற்றவும்',
      currentPassword: 'தற்போதைய கடவுச்சொல்',
      newPassword: 'புதிய கடவுச்சொல்',
      confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      updatePassword: 'கடவுச்சொல்லைப் புதுப்பிக்கவும்',
      enableNotifications: 'அறிவிப்புகளை இயக்கவும்',
      emailNotifications: 'மின்னஞ்சல் அறிவிப்புகள்',
      pushNotifications: 'புஷ் அறிவிப்புகள்',
      saveSettings: 'அமைப்புகளைச் சேமிக்கவும்',
      settingsSaved: 'அமைப்புகள் வெற்றிகரமாக சேமிக்கப்பட்டன!',
      sessionReminders: 'அமர்வு நினைவூட்டல்கள்',
      dailyWellnessCheckins: 'தினசரி நலன் சரிபார்ப்புகள்',
      exerciseSuggestions: 'பயிற்சி பரிந்துரைகள்',
      weeklyProgressReports: 'வாராந்திர முன்னேற்ற அறிக்கைகள்',
      dataSharing: 'தரவு பகிர்வு',
      private: 'தனிப்பட்ட',
      shareWithInstitution: 'நிறுவனத்துடன் பகிர்',
      public: 'பொது',
      twoFactorAuth: 'இரண்டு காரணி அங்கீகாரம்',
      enable: 'இயக்கு',
      helpSupport: 'உதவி மற்றும் ஆதரவு',
      userGuide: 'பயனர் வழிகாட்டி',
      contactSupport: 'தொடர்பு ஆதரவு',
      faq: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',

      // Notifications
      notificationsTitle: 'அறிவிப்புகள்',
      stayUpdated: 'உங்கள் உணர்வு பயணத்துடன் புதுப்பித்த நிலையில் இருங்கள்',
      recentNotifications: 'சமீபத்திய அறிவிப்புகள்',
      markAsRead: 'படித்ததாக குறிக்கவும்',
      delete: 'நீக்கு',
      all: 'அனைத்தும்',
      unread: 'படிக்காதது',
      sessionReminder: 'அமர்வு நினைவூட்டல்',
      sessionReminderMessage: 'டாக்டர் ஸ்மித் உடனான உங்கள் மென்டர் அமர்வு 30 நிமிடங்களில் உள்ளது',
      exerciseSuggestion: 'பயிற்சி பரிந்துரை',
      exerciseSuggestionMessage: '"மூச்சு இடம்" பயிற்சியை முயற்சிக்கவும் - மன அழுத்தம் நிறைந்த தருணங்களுக்கு சரியானது',
      streakMilestone: 'தொடர் மைல்கல்!',
      streakMilestoneMessage: 'வாழ்த்துகள்! நீங்கள் தொடர்ந்து 7 நாட்கள் முழுமையடைந்துள்ளீர்கள்',
      dailyCheckin: 'தினசரி சரிபார்ப்பு',
      dailyCheckinMessage: 'இன்று நீங்கள் எவ்வாறு உணர்கிறீர்கள்? உங்கள் மனநிலையை பதிவு செய்ய மறக்காதீர்கள்',
      sessionFollowup: 'அமர்வு பின்தொடர்பு',
      sessionFollowupMessage: 'உங்கள் கடைசி அமர்வு எவ்வாறு சென்றது? உங்கள் நாட்குறிப்பில் உங்கள் எண்ணங்களைப் பகிர்ந்து கொள்ளுங்கள்',
      achievementNotifications: 'சாதனை அறிவிப்புகள்',

      // Analytics
      analyticsTitle: 'பகுப்பாய்வு',
      comprehensiveInsights: 'க்கான விரிவான நுண்ணறிவுகள்',
      yourInstitution: 'உங்கள் நிறுவனம்',
      userEngagement: 'பயனர் ஈடுபாடு',
      programPerformance: 'திட்ட செயல்பாடு',
      mostPopularExercises: 'மிகவும் பிரபலமான பயிற்சிகள்',
      totalUsers: 'மொத்த பயனர்கள்',
      activeUsers: 'செயலில் உள்ள பயனர்கள்',
      sessionsCompleted: 'முழுமையடைந்த அமர்வுகள்',
      averageMoodScore: 'சராசரி மனநிலை மதிப்பெண்',
      exercisesCompleted: 'முழுமையடைந்த பயிற்சிகள்',
      participationRate: 'பங்கேற்பு விகிதம்',
      averageSessionTime: 'சராசரி அமர்வு நேரம்',
      meditationStats: 'தியான புள்ளியல்',
      journalStats: 'நாட்குறிப்பு புள்ளியல்',
      mentorSessions: 'மென்டர் அமர்வுகள்',
      topExercises: 'சிறந்த பயிற்சிகள்',
      moodTrends: 'மனநிலை போக்குகள்',
      institutionOverview: 'நிறுவன கண்ணோட்டம்',
      totalInstitutions: 'மொத்த நிறுவனங்கள்',
      activePrograms: 'செயலில் உள்ள திட்டங்கள்',
      topPerformer: 'சிறந்த செயல்பாட்டாளர்',
      thisWeek: 'இந்த வாரம்',
      thisMonth: 'இந்த மாதம்',
      thisQuarter: 'இந்த காலாண்டு',
      refresh: 'புதுப்பிக்க',
      exportData: 'தரவை ஏற்றுமதி செய்ய',
      exportingData: 'தரவை ஏற்றுமதி செய்கிறது...',
      refreshingData: 'தரவை புதுப்பிக்கிறது...',
      breathingExercises: 'மூச்சு பயிற்சிகள்',
      bodyScan: 'உடல் ஸ்கேன்',
      mindfulWalking: 'உணர்வு நடை',
      lovingKindness: 'அன்பு நன்மை',
      week1: 'வாரம் 1',
      week2: 'வாரம் 2',
      week3: 'வாரம் 3',
      week4: 'வாரம் 4',

      // Common
      loading: 'ஏற்றப்படுகிறது...',
      error: 'பிழை',
      success: 'வெற்றி',
      cancel: 'ரத்து செய்',
      save: 'சேமிக்க',
      edit: 'திருத்து',
      delete: 'நீக்கு',
      back: 'பின்னால்',
      next: 'அடுத்தது',
      previous: 'முந்தையது',
      search: 'தேடு',
      filter: 'வடிகட்டு',
      sort: 'வரிசைப்படுத்து',
      date: 'தேதி',
      time: 'நேரம்',
      duration: 'கால அளவு',
      status: 'நிலை',
      actions: 'செயல்கள்'
    }
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  const changeLanguage = (newLanguage) => {
    if (['english', 'hindi', 'tamil'].includes(newLanguage)) {
      setLanguage(newLanguage);
    }
  };

  const value = {
    language,
    setLanguage: changeLanguage,
    t,
    translations: translations[language]
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
